/// Flutter icons MyIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyIcons
///      fonts:
///       - asset: fonts/MyIcons.ttf
///
///
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
///
import 'package:flutter/widgets.dart';

class MyIcons {
  MyIcons._();

  static const _kFontFam = 'MyIcons';
  static const String _kFontPkg = null;

  static const IconData heart = IconData(
    0xe800,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData heart_circled = IconData(
    0xe801,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData heart_empty = IconData(
    0xe802,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData star = IconData(
    0xe803,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData star_circled = IconData(
    0xe804,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData star_empty = IconData(
    0xe805,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
}
